### ISSUE TITLE
Replace `typedef string Path` with `class Path`

### ISSUE THREAD

**Issue by AtnNn** [nix-windows/nix#9] opened 2020-10-20 17:33 UTC
This would allow regrouping all ad-hoc path handling, conversion and checking into the new class (such as `pathW` and all instances of `'a' <= path && path <= 'z'`).

**Comment by Ericson2314** [comment] 2024-04-08 14:01
This looks like a duplicate of https://github.com/NixOS/nix/issues/9205 now

**Closed as completed** 2024-04-08 14:02 UTC
